### ISSUE TITLE
SerializationException

### ISSUE THREAD

**Issue by Kieaer** [Quezler/mindustry__plugin--flatearth#2]
```
arc.util.serialization.SerializationException: Serialization trace:
public arc.struct.Array mindustry.game.Rules.spawns (mindustry.game.Rules)
        at arc.util.serialization.Json.writeFields(Json.java:319)
        at arc.util.serialization.Json.writeValue(Json.java:657)
        at mindustry.io.JsonIO$1.writeValue(JsonIO.java:30)
        at arc.util.serialization.Json.toJson(Json.java:265)
        at arc.util.serialization.Json.toJson(Json.java:220)
        at arc.util.serialization.Json.toJson(Json.java:205)
        at mindustry.io.JsonIO.write(JsonIO.java:48)
        at mindustry.io.TypeIO.writeRules(TypeIO.java:180)
        at mindustry.gen.Call.onSetRules(Call.java:774)
        at flatearth.FlatearthMod.lambda$init$0(FlatearthMod.java:40)
        at arc.Events.lambda$on$0(Events.java:17)
        at arc.Events.lambda$fire$1(Events.java:25)
        at arc.struct.Array.each(Array.java:175)
        at arc.Events.fire(Events.java:25)
        at arc.Events.fire(Events.java:21)
        at mindustry.core.Logic.update(Logic.java:212)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:93)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:63)
Caused by: java.lang.IllegalStateException: Current item must be an object.
        at arc.util.serialization.JsonWriter.name(JsonWriter.java:49)
        at arc.util.serialization.Json.writeValue(Json.java:414)
        at mindustry.game.SpawnGroup.write(SpawnGroup.java:77)
        at arc.util.serialization.Json.writeValue(Json.java:514)
        at mindustry.io.JsonIO$1.writeValue(JsonIO.java:30)
        at arc.util.serialization.Json.writeValue(Json.java:533)
        at mindustry.io.JsonIO$1.writeValue(JsonIO.java:30)
        at arc.util.serialization.Json.writeFields(Json.java:312)
        ... 17 more
```

**Comment by Kieaer** [comment]
This error occurs when the __map is loading__ after gameover.
solution: ``Call.onSetRules(state.rules);`` to ``if(state.is(State.playing)) Call.onSetRules(state.rules);``
